sudo: false
language: python
python:
- '2.7'
- '3.6'
install:
- pip install -r requirements-dev.txt
- pip install coveralls
- pip install -e .
script:
- mamba --enable-coverage
after_success:
- coveralls
- coverage report
deploy:
  provider: pypi
  user: gisce
  password:
    secure: w759P9veAKperTYSZnqX6uHsffEBOGIrU62Ne2rTeHPFJr311pAClb15DVmx+7JPFRnyjiTCVvz6dJvZYakEnZRiaH8KnPNqQQlHeSfbO5AohDFCmjGZH/mALVuWeJvoBoQ0+ozVg9GnY7BakVTKodMnws7/kz1LMzdvE9NplVKlopinWYLyJSHVXwH8TKmD5jzQiAUnSvSrJ0mUbxdP+9frdH643rHLe80ePQ1cKr/DFEmy1/lgzlmeG1/hwGUTapygZwJs/FNuASBw3tvDaxZP/I4wFe+gbRf5MN7DJICjuVbeAlEwU/MfKoZ0VsGVgmkZVqv8uIem71bocMgPZ/+NdEs9TjDyJfMjM5HVhNrHpq/HowgiEMGmzc4AcnNq/tnK0Fkpr/+tDTIL1kyCnbLyXA+G+JFtgjV8+Z21X4fy1anbiB26TfUXWtQjm+m74Si8avqpwo70uW031JA5kQkq3WT/1UUf7iqC+McSsX5Tx4N8qSIYG1t1/rn9KHzUQUtNUffRzM0q9ksgoWTSEErUdjCe7JiqQrm90gUqS6jTe3hDZz+Dp984kFiLYKqkBfL0a91YCoj9D1J+/8arj0nEAB1cfSV58/YNblgIgoyIbMRmF3w2CMLQeZql9hkkOpOCs/mcvhWAxcNnZH2dRRheCuU0Yv2N27yW4xvFoWQ=
  on:
    tags: true
    repo: gisce/ooquery
