

# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: OOQUERY-TESTS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-python3:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        pip install -r requirements-dev.txt
        pip install coveralls
        pip install -e .
    - name: Run tests
      run: |
        mamba --enable-coverage

  test-python27:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 2.7.18
      run: |
        sudo apt-get update
        sudo apt-get install -y python2.7 python2.7-dev python-pip-whl
        curl https://bootstrap.pypa.io/pip/2.7/get-pip.py --output get-pip.py
        sudo python2.7 get-pip.py
    - name: Install dependencies
      run: |
        python2.7 -m pip install -r requirements-dev.txt
        python2.7 -m pip install coveralls
        python2.7 -m pip install -e .
    - name: Run tests
      run: |
        python2.7 -m mamba --enable-coverage